[package]
name = "embed-collections"
version = "0.2.1"
edition = "2024"
license = "MIT OR Apache-2.0"
description = "A collection of intrusive data structures (linked lists) for Rust, supporting various pointer types."
keywords = ["intrusive", "linked-list", "collection"]
categories = ["data-structures", "no-std"]

[features]
default = ["std", "full"]
std = []
slist = []
dlist = []
avl = []
full = ["slist", "dlist", "avl"]

[dependencies]

[dev-dependencies]
rstest = "0"
rand = "0.8.5"
criterion = { version = "0.5", features = ["html_reports"] }

[[bench]]
name = "avl"
harness = false

[package.metadata.docs.rs]
all-features = true
# enable features in the documentation
rustdoc-args = ["--cfg", "docsrs"]
