[package]
name = "embed-collections"
version = "0.1.3"
edition = "2024"
license = "MIT OR Apache-2.0"
description = "A collection of intrusive data structures (linked lists) for Rust, supporting various pointer types."
keywords = ["intrusive", "linked-list", "collection"]
categories = ["data-structures", "no-std"]

[features]
default = ["std", "full"]
std = []
slist = []
dlist = []
full = ["slist", "dlist"]

[dependencies]

[dev-dependencies]
rstest = "0"

[package.metadata.docs.rs]
all-features = true
# enable features in the documentation
rustdoc-args = ["--cfg", "docsrs"]
